"""外部データの読み取り・更新の契約。"""

from typing import Protocol


class ApiQueries(Protocol):
    def credential_lock(self, username): ...
    def credential_identity(self, user): ...
    def credential_record(self, user): ...
    def publication_lock(self, username): ...
    def publication_key(self, username, name): ...
    def get_publication(self, user, name): ...
    def list_publications(self, user): ...
