"""外部APIの所有者照合済みレコード取得と、ユーザー単位の排他制御の契約。"""

from typing import Protocol


class ApiQueries(Protocol):
    def credential_lock(self, username): ...
    def credential_identity(self, user): ...
    def credential_record(self, user): ...

    def publication_lock(self, username): ...
    def publication_key(self, username, name): ...
    def get_publication(self, user, name): ...
    def list_publications(self, user): ...
