"""API公開に必要な外部処理の契約。"""

from typing import Protocol


class RecordStore(Protocol):
    def get(self, kind: str, name: str) -> dict | None: ...
    def put(self, kind: str, name: str, record: dict) -> None: ...
    def delete(self, kind: str, name: str) -> None: ...
    def names(self, kind: str) -> list[str]: ...


class CloudflareAccess(Protocol):
    async def issue(self, name: str) -> dict: ...
    async def rotate(self, token_id: str) -> dict: ...
    async def remove(self, token_id: str) -> None: ...
    async def app(
        self, name: str, domains: list, token_ids: list, existing_id=None
    ) -> dict: ...
    async def remove_app(self, name: str, app_id=None) -> None: ...


class HubTokens(Protocol):
    async def user(self, username: str): ...
    def issue(self, user) -> dict: ...
    def revoke(self, token_id) -> None: ...
    def valid(self, record: dict, user) -> bool: ...
    def revoke_orphans(self, username: str, keep_id=None) -> None: ...


class ListenerInventory(Protocol):
    def choose(self, uid: int, candidate: str = "", port=None) -> dict: ...
    def validate(self, target: dict): ...
    def ports(self, uid: int) -> dict: ...


class PortGuard(Protocol):
    async def protect(self, target: dict) -> None: ...
    async def check(self, target: dict) -> None: ...
    async def reconcile(self) -> None: ...


class AccessVerifier(Protocol):
    async def verify(self, assertion: str, app: dict, credentials: dict): ...


class HttpRelay(Protocol):
    def request(
        self, inventory, target, method, path, headers=None, body=None, *, timeout
    ): ...


class ApiHealth(Protocol):
    async def check(self, record: dict) -> None: ...


class ApiConfiguration(Protocol):
    public_host: str
    max_apps: int
    body_limit: int
    timeout: int
    concurrency: int
