"""LLM利用者・キー・モデルの管理と、応答解析・排他制御の契約。"""

import threading
from typing import Protocol


class LlmManagementGateway(Protocol):
    def ensure_user(self, username: str) -> str | None: ...
    def metadata(self, value) -> dict: ...
    def user_metadata(self, username: str) -> tuple[dict, str | None]: ...
    def set_user_admin_disabled(self, username: str, disabled: bool) -> str | None: ...
    def user_admin_disabled(self, username: str) -> tuple[bool, str | None]: ...

    def iter_key_records(self, value): ...
    def key_identifier(self, record: dict) -> str: ...
    def key_belongs_to_user(self, record: dict, username: str) -> bool: ...
    def list_user_keys(self, username: str) -> tuple[list[dict], str | None]: ...
    def is_portal_external_key(self, record: dict, username: str) -> bool: ...
    def external_api_key_lock(self, username: str): ...
    def set_key_metadata(self, record: dict, disabled: bool) -> str | None: ...

    def model_records(self, value): ...
    def model_lock(self, model: str) -> threading.Lock: ...
    def model_info(self) -> tuple[dict | list | None, str | None]: ...
    def ollama_deployments(self, value, model: str) -> list[dict]: ...
    def delete_deployments(self, deployment_ids: list[str]) -> str | None: ...

    def openwebui_key_info(
        self, username: str, key: str
    ) -> tuple[dict | None, str, str | None]: ...

    def safe_litellm_error(self, error) -> str: ...
    def log_litellm_action(
        self, action: str, username: str, result: str, error=None
    ) -> None: ...
