"""LLM操作に必要な外部接続の契約。"""

from typing import Protocol


class LlmClient(Protocol):
    def enabled(self) -> bool: ...
    def request(
        self, path: str, payload: dict | None = None, method: str = "POST"
    ) -> dict: ...


class ModelInventory(Protocol):
    def has_model(self, model: str) -> tuple[bool, str | None]: ...
    def model_names(self) -> tuple[list[str], str | None]: ...
    def model_supports_tools(self, model: str) -> tuple[bool | None, str | None]: ...


class KeyStore(Protocol):
    def read(self, username: str) -> str: ...
    def write(self, username: str, key: str) -> str | None: ...
    def remove(self, username: str) -> None: ...
