"""ユーザー管理に必要な外部処理の契約。"""

from typing import Protocol


class AccountDirectory(Protocol):
    def getpwnam(self, username: str): ...


class UserAccountGateway(AccountDirectory, Protocol):
    def linux_users_snapshot(self) -> list[dict]: ...
    def home_storage_usage(self, home: str) -> tuple[int | None, str | None]: ...
    def create_linux_user(
        self, username: str, password: str, grant_sudo: bool, display_name: str
    ) -> str | None: ...
    def delete_linux_user(self, username: str, actor: str) -> str | None: ...
    def set_linux_sudo(self, username: str, enabled: bool) -> str | None: ...
    def set_linux_display_name(
        self, username: str, display_name: str
    ) -> str | None: ...
    def set_linux_password(self, username: str, password: str) -> str | None: ...
    def verify_linux_password(
        self, username: str, password: str, *, service: str
    ) -> str | None: ...
